name: New Chart Version

on:
  pull_request:
    paths:
      - "apps/rstudio/Chart.yaml"

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Set Environment Variables
        run: |
          HELM_CHART=rstudio
          echo "HELM_CHART=$HELM_CHART" >> "$GITHUB_ENV"
          NEW_CHART_VERSION=$(yq e '.version' apps/rstudio/Chart.yaml)
          echo "NEW_CHART_VERSION=$NEW_CHART_VERSION" >> $GITHUB_ENV
          echo "JSON_FILE_PATH=fixtures/apps_fixtures.json" >> $GITHUB_ENV

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Target Repository
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "jana.awada@scilifelab.uu.se"
          git clone git@github.com:j-awada/repo-a.git

      - name: Import GPG key and configure commit signing
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          git config --global user.signingkey "$(gpg --list-keys --with-colons | grep pub | cut -d':' -f10)"
          git config --global commit.gpgsign true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Update JSON File
        run: |
          cd repo-a
          jq -M --arg new_chart_version "$NEW_CHART_VERSION" 'map(if .fields.chart | contains("${{ env.HELM_CHART }}:") then .fields.chart |= sub(":[^:]+$"; ":" + $new_chart_version) else . end)' $JSON_FILE_PATH > tmp.json
          mv tmp.json $JSON_FILE_PATH
          git add $JSON_FILE_PATH
          git diff --quiet || git commit -m "Update chart version in ${{ env.HELM_CHART }} to ${{ env.NEW_CHART_VERSION }}"
      
      - name: Push Changes
        run: |
          cd repo-a
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MY_PAT }}
          commit-message: "Update JSON configuration"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <jana.awada@scilifelab.uu.se>
          branch: update/${{ env.HELM_CHART }}-${{ env.NEW_CHART_VERSION }}
          title: 'Update chart version in ${{ env.HELM_CHART }} to ${{ env.NEW_CHART_VERSION }}'
          body: |
            This PR updates the `chart` field in `fixtures.json` to use the new version: `${{ env.NEW_CHART_VERSION }}`.
            Please review and merge if everything looks good.
          path: repo-a
