#name: Bump Helm chart version in Serve

#on:
#  push:
#    pull_requests:
#      path:
#        - apps/**/Chart.yaml

#jobs:
#  update_serve_repo:
#    runs_on: ubuntu-latest
#    steps:
#      - name: Checkout Source Repo
#        uses: actions/checkout@v3

#      - name: Clone Serve repo
#        run: |
#          git clone https://github.com/j-awada/repo-a.git
#          cd repo-a
#          git config user.name "$GITHUB_ACTOR"
#          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

#      - name: Create and switch to new branch
#        run: |
#          cd repo-a
#          git checkout -b app-helm-chart-upgrade
#          echo "BRANCH_NAME=app-helm-chart-upgrade" >> $GITHUB_ENV

#      - name: Update apps_fixtures.json
#        run: |
#          cd repo-a
#          #sed -i 's/^chart: ghcr.io/scilifelabdatacentre/serve-charts/APP_NAME:version:.*/version: NEW_VERSION/' fixtures#/apps_fixtures.json
#          git add fixtures/apps_fixtures.json
#          git commit -m "Update Helm chart version"
#          git push origin $BRANCH_NAME

#      - name: Open PR in Serve repo
#        uses: peter-evans/create-pull-request@v5
#        with:
#          token: "${{ secrets.GITHUB_TOKEN }}"
#          commit-message: "update helm chart version"
#          title: "Update app Helm chart version"
#          body: "Automated PR"
#          branch: ${{ env.BRANCH_NAME }}
#          base: "develop"